name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check scripts directory
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Scripts directory contents ==="
          ls -la scripts/
          echo "=== Checking if generate scripts exist ==="
          test -f scripts/generate-shades-css.js && echo "✅ generate-shades-css.js exists" || echo "❌ generate-shades-css.js missing"
          test -f scripts/generate-daisyUI-css.js && echo "✅ generate-daisyUI-css.js exists" || echo "❌ generate-daisyUI-css.js missing"

      - name: Build package
        run: npm run build

      - name: Run linting
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Check package contents
        run: |
          echo "=== Generated CSS Files ==="
          ls -la dist/
          echo "=== Generated Library Files ==="
          ls -la lib/
          echo "=== Package contents preview ==="
          npm pack --dry-run
