name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for npm registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          # Remove package-lock to ensure fresh install
          rm -f package-lock.json
          # Use npm install instead of npm ci for better optional dependency handling
          npm install

      - name: Check scripts directory
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Scripts directory contents ==="
          ls -la scripts/
          echo "=== Checking if generate scripts exist ==="
          test -f scripts/generate-shades-css.js && echo "✅ generate-shades-css.js exists" || echo "❌ generate-shades-css.js missing"
          test -f scripts/generate-daisyUI-css.js && echo "✅ generate-daisyUI-css.js exists" || echo "❌ generate-daisyUI-css.js missing"

      - name: Build package
        run: npm run build

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Update package.json version for npm registry
        run: |
          # Extract version from GitHub release tag (remove 'v' prefix if present)
          VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "Setting version to: $VERSION"
          
          node -e "
            const pkg = require('./package.json');
            pkg.version = '$VERSION';
            // Remove GitHub Packages specific config
            delete pkg.publishConfig;
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
            console.log('✅ Updated package.json with version:', pkg.version);
            console.log('✅ Package name:', pkg.name);
          "

      - name: Publish to npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
