name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check scripts directory
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Scripts directory contents ==="
          ls -la scripts/
          echo "=== Checking if generate scripts exist ==="
          test -f scripts/generate-shades-css.js && echo "✅ generate-shades-css.js exists" || echo "❌ generate-shades-css.js missing"
          test -f scripts/generate-daisyui-css.js && echo "✅ generate-daisyui-css.js exists" || echo "❌ generate-daisyui-css.js missing"

      - name: Build package
        run: npm run build

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Update package.json for GitHub Packages
        run: |
          node -e "
            const pkg = require('./package.json');
            pkg.name = '@deutschemodulunitednations/corporate-identity';
            pkg.publishConfig = {
              registry: 'https://npm.pkg.github.com',
              access: 'public'
            };
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
